inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - app/channels/**/*
    - node_modules/**/*
    - bin/*
    - spec/**/*
    - lib/*
    - db/schema.rb
    - db/migrate/*
    - lib/tasks/*
    - public/*
    - tmp/*
    - vendor/**/*
    - config/spring.rb

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false
