default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: golf_development

test:
  <<: *default
  database: golf_test
