default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= Rails.application.credentials.default(:password) %>
  host: db

development:
  <<: *default
  database: golf_development

test:
  <<: *default
  database: golf_test

production:
  <<: *default
  username: <%= Rails.application.credentials.production(:username) %>
  password: <%= Rails.application.credentials.production(:password) %>
  host: <%= Rails.application.credentials.production(:host) %>
  database: <%= Rails.application.credentials.production(:database) %>
