default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: username
  password:
  pool: 5

development:
  <<: *default
  database: rails_dev

test:
  <<: *default
  database: rails_test

# production:
#   <<: *default
#   database: 
#   host: <%= Rails.application.credentials.[:] %>
#   username: <%= Rails.application.credentials.[:] %>
#   password: <%= Rails.application.credentials.[:] %>
