default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: rails_dev
  pool: 5
  username: username
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: rails_dev
  pool: 5
  username: username
  password:
  host: localhost

# test:
#   <<: *default
#   database: myapp_test
