Golf.find_or_create_by(name: '宇陀カントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '花吉野カンツリー倶楽部', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '阿騎野ゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '春日台カントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '木津川カントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'グランデージゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'KOMAカントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'シプレカントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '新奈良ゴルフ倶楽部', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '天理ゴルフ倶楽部', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'ナパラゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '奈良カントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '奈良の杜カントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '奈良パブリックゴルフ場', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '奈良万葉カンツリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '奈良名阪ゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '奈良柳生カントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '奈良ロイヤルゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '奈良若草カントリー倶楽部', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'プレディアゴルフ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '法隆寺カントリー倶楽部', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '万壽ゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'ムロウ36ゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '八重桜カントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'ヤマトカントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '大和高原カントリークラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'よしのカントリー倶楽部', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '秋津原ゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '飛鳥カンツリー倶楽部', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'オークモントゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: 'ディアーパークゴルフクラブ', place: '〇〇〇〇', courserate: 72)
Golf.find_or_create_by(name: '奈良国際ゴルフ倶楽部', place: '〇〇〇〇', courserate: 72)

Point.find_or_create_by(valuation: 1)
Point.find_or_create_by(valuation: 2)
Point.find_or_create_by(valuation: 3)
Point.find_or_create_by(valuation: 4)
Point.find_or_create_by(valuation: 5)

User.create!(username: 'maru', email: 'maru@abc.com', password: ENV['PASSWORD'], password_confirmation: ENV['PASSWORD'], confirmed_at: Time.now - 100, admin: true)
User.create!(username: 'tanaka', email: 'abc@abc.com', password: ENV['PASSWORD'], password_confirmation: ENV['PASSWORD'], confirmed_at: Time.now - 100)
User.create!(username: 'nana', email: 'nana@rails.com', password: ENV['PASSWORD'], password_confirmation: ENV['PASSWORD'], confirmed_at: Time.now - 100)
User.create!(username: 'oota', email: 'yyyy@ooo.com', password: ENV['PASSWORD'], password_confirmation: ENV['PASSWORD'], confirmed_at: Time.now - 100)
User.create!(username: 'rails', email: 'xxx@ooo.com', password: ENV['PASSWORD'], password_confirmation: ENV['PASSWORD'], confirmed_at: Time.now - 100)
